# Generated by Django 5.1.5 on 2025-02-03 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('preis', models.FloatField()),
                ('beschreibung', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productImages/')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myShop.product')),
            ],
        ),
    ]
