# Generated by Django 5.1.5 on 2025-02-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0002_product_datum_alter_product_beschreibung'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='headerImages/')),
                ('beschreibung', models.TextField()),
            ],
        ),
    ]
