# Generated by Django 5.1.5 on 2025-02-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0003_headergallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breite',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='farbe',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='höhe',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='holz', max_length=30),
            preserve_default=False,
        ),
    ]
