# Generated by Django 5.1.5 on 2025-02-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plz',
            field=models.IntegerField(default=0),
        ),
    ]
