# Generated by Django 5.1.5 on 2025-02-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0006_alter_userprofile_plz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='adresse',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='agb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nachname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vorname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
