# Generated by Django 5.1.5 on 2025-02-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0007_alter_userprofile_adresse_alter_userprofile_agb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ist_verkauft',
            field=models.BooleanField(default=False),
        ),
    ]
