# Generated by Django 5.1.5 on 2025-02-08 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0008_product_ist_verkauft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=70)),
                ('betrag', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=25)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('produkt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myShop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
