# Generated by Django 5.1.5 on 2025-02-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0009_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='produkt',
        ),
        migrations.AddField(
            model_name='orders',
            name='produkt',
            field=models.ManyToManyField(to='myShop.product'),
        ),
    ]
