# Generated by Django 5.1.5 on 2025-02-17 23:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0011_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
