"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import stripe

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g5n6x9hzd5(3e^!+47mj^^lr%)xjewre#%v!f7lkw(dsw9$e$l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'https://6e40-145-254-36-25.ngrok-free.app/']
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = "/login/"


PAYPAL_RECEIVER_EMAIL = 'sb-t3qby37542570_api1.business.example.com'
PAYPAL_TEST = True


STRIPE_PUBLIC_KEY = "pk_test_51QtaoIGINRrgLBNvSPscPQ6ykcu10vdZswkQJ5j1zlA2tjRN5FNUXQCTPKe29PiJ0MaINhrMzf11DDUO66vko5V400986OAqsk"
STRIPE_SECRET_KEY = "sk_test_51QtaoIGINRrgLBNvyCBmYmLjc4HAgn7jl0kZeDvAmLD5eYGbvWPiHDIRXFEs5L6IYVfZsR7OvrYRxtmFtrcMrVuy00D0yPQGyR"
WEBHOOK_SECRET = "whsec_kiTB3AEmgbzMaWfeOvgPWeIKzDN1p07J"
stripe.api_key = STRIPE_SECRET_KEY
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myShop',
    'paypal.standard.ipn',
]

CSRF_TRUSTED_ORIGINS = [
    "https://6cc6-145-254-36-25.ngrok-free.app",
    "https://paypal.com",
    "https://ipnpb.paypal.com",
    "https://d9b7-145-254-36-25.ngrok-free.app",
    "https://173.0.80.0",
    "https://64.4.240.0",
    "https://64.4.248.0",
    "https://66.211.168.0",
    "https://91.243.72.0",
    "https://ipnpb.sandbox.paypal.com/cgi-bin/webscr",
    "https://www.paypal.com", 
    "https://www.sandbox.paypal.com",
    "https://ec04-145-254-36-25.ngrok-free.app"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

VERSAND = 5.00


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
